# Generated by Django 5.2.16 on 2026-08-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailotp',
            name='accounts_em_user_id_7bddd4_idx',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('EMAIL_VERIFY', 'Email verification'), ('PASSWORD_RESET', 'Password reset')], default='EMAIL_VERIFY', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'purpose', 'is_used', '-created_at'], name='accounts_em_user_id_e2f741_idx'),
        ),
    ]
